repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0  # or latest stable version
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system  # or python if you want a venv
        types: [python]